version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8087:80"
      - "5173:5173"
    networks:
      - internal
    volumes:
      - ../backend/:/var/www/html/backend
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: ./php/context
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ../backend/:/var/www/html/backend
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - 9000
      - 5173:5173 # Expose Vite dev server port
  mysql:
    container_name: db
    restart: always
    build:
      context: ./db/context
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'HumanitarianAids'
      MYSQL_PASSWORD: 'HumanitarianAids'
      MYSQL_DATABASE: 'HumanitarianAids'
    volumes:
      - ./db_data/data:/var/lib/mysql
      - ../db_backups/full_backup:/home/backups/full_backups # Volume for storing backups
      - ../db_backups/binary_logs:/home/backups/binary_logs # Volume for storing backups
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
